'use client';
import {useState,useRef} from 'react';
import {Leaf, FileText, ScanLine, ClipboardList, Settings, ChevronDown, Bell, Upload, Image as ImageIcon, ArrowUp, Send, Link2} from 'lucide-react';
import './debug-workbench.css';
import SpatialEditor,{importMap} from './spatial-editor';
import {emptySpatial,demoSpatial,type Spatial} from '@/lib/spatial';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';

type Props={project:{id:string;name:string;address:string;spatial?:Spatial;photos:{id:string;name:string;category:string;src:string}[]};saved:string;onNavigate:(page:'home'|'archive'|'plans')=>void;onGallery:()=>void;onChange:(s:Spatial)=>void;onPlan:(title:string,body:string)=>void};
export default function DebugWorkbench({project,saved,onNavigate,onGallery,onChange,onPlan}:Props){
 const [message,setMessage]=useState(''),[chatOpen,setChatOpen]=useState(true),[showWelcome,setShowWelcome]=useState(false),[dialog,setDialog]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[messages,setMessages]=useState<{role:string;text:string;time:string}[]>([]);
 const upload=useRef<HTMLInputElement>(null);const spatial=project.spatial||emptySpatial(project.address);const active=spatial.mode!=='empty'&&!showWelcome;
 function send(text=message){if(!text.trim())return;let reply='我可以协助你梳理地图与调试流程。当前为本机规则演示：先确认底图与路网，再标记老人居住点和特殊情况，最后比较路线、试放设施并整理方案。';if(/上传|卫星|底图/.test(text))reply='点击「前往图片库」导入 GeoTIFF 或普通图片。GeoTIFF 会读取坐标信息；普通图片需人工补充坐标与尺度。也可以载入青溪村演示数据。上传影像不会自动生成真实道路识别结果。';else if(/识别|要素|AI/.test(text))reply='V1.0 围绕道路、建筑、公共设施和特殊情况组织信息。此 demo 未接入视觉模型，提供可编辑的演示对象；你可以补画道路、修改建筑分类，绑定照片并确认或否定观察。';else if(/路|测试|角色/.test(text))reply=`当前有 ${spatial.roads.length} 段道路，其中 ${spatial.roads.filter(r=>r.confirmed).length} 段已确认。进入「路径测试」选择起終点、移动能力与环境，可比较最短、相对低风险和习惯路线。使用助行器会避开已知台阶；未确认路网仅输出预览。`;else if(/选址|设施|覆盖/.test(text))reply='进入「选址测试」，输入设施名称并选择面积档，在地图试放或拖动轮廓。红色表示已知空间冲突；黄色表示路线问题或数据缺口；绿色只表示当前通达性与空间关系较优。';else if(/方案|设计/.test(text))reply='「场域设计」支持现状图、可拖动布局组件和结构化文字方案。概念效果图是预制 AI 示例，不会随新照片或布局自动变化。生成文字方案后，可发送到方案区继续编辑。';const time=new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});setMessages(v=>[...v,{role:'user',text,time},{role:'assistant',text:reply,time}]);setMessage('');}
 return <div className="dw-app">
  <header className="dw-header"><button className="dw-brand" onClick={()=>onNavigate('home')}><Leaf/><span>乡筑</span></button><p>用设计与科技，<br/>建设更友好的乡村。</p><span className="dw-poem">看见乡村，<br/>看见更好的未来。</span><Bell size={21}/><span className="dw-user">Z</span><span>张工</span><ChevronDown size={15}/></header>
  <aside className="dw-sidebar"><div className="dw-project"><small>当前项目</small><button onClick={()=>onNavigate('home')}>{project.name.split(' · ')[0]}<ChevronDown size={16}/></button></div><nav><button onClick={()=>onNavigate('archive')}><FileText/><span>档案<small>村庄资料</small></span></button><button className="active"><ScanLine/><span>调试<small>实地调研</small></span></button><button onClick={()=>onNavigate('plans')}><ClipboardList/><span>方案<small>辅助规划</small></span></button></nav><button className="dw-settings" onClick={()=>onNavigate('home')}><Settings size={20}/>项目管理</button></aside>
  <main className={`dw-main ${active?'dw-active':''} ${!chatOpen?'dw-chat-closed':''}`}><section className="dw-board"><div className="dw-board-inner">{active?<SpatialEditor data={spatial} onChange={onChange} onPlan={onPlan} onEmpty={()=>setShowWelcome(true)} chatOpen={chatOpen} onToggleChat={()=>setChatOpen(!chatOpen)}/>:<><div className="dw-title"><span>调试 WORKSPACE</span><h1>空间调试台</h1><p>以卫星俯视图为基础，标记道路、设施、风险与拟建节点。</p></div><div className="dw-empty"><div className="dw-upload-orbit"><ImageIcon size={56}/><span><ArrowUp size={27}/></span></div><h2>请先上传村庄卫星俯视图</h2><p>以当前项目中的正射影像为底板，组织空间标注与分析。<br/>从一张地图开始，看见更友好的乡村生活。</p><button className="dw-primary" onClick={()=>setDialog('gallery')}><Upload size={21}/>前往图片库</button><button className="dw-text-button" onClick={()=>{if(spatial.mode==='empty')onChange(demoSpatial());setShowWelcome(false);setChatOpen(false)}}>{spatial.mode==='empty'?'使用青溪村演示数据':'继续上次调试'} <span>→</span></button></div><p className="dw-signature">用空间数据<br/>发现乡村更多可能。</p></>}</div></section>
  {chatOpen&&<aside className="dw-chat"><div className="dw-chat-inner"><header><div className="dw-leaf"><Leaf/></div><div><h2>档案协作频道 <i/></h2><p>与 AI 助手一起进行空间分析与规划</p></div><button aria-label="连接检索源" onClick={()=>setDialog('sources')}><Link2 size={17}/><span>连接检索源</span></button></header><div className="dw-messages"><article><div className="dw-leaf small"><Leaf size={22}/></div><div><p>欢迎使用空间调试台！<br/>你可以上传村庄的正射影像，整理道路、建筑、公共设施和风险点，为后续的规划提供数据基础。</p><time>10:24</time></div></article><article><div className="dw-leaf small"><Leaf size={22}/></div><div><p>建议优先上传一张近期的带坐标正射影像。也可以载入演示数据，体验从路网校正到概念设计的完整流程。</p><time>10:24</time></div></article>{messages.map((m,i)=><article key={i} className={m.role==='user'?'dw-user-message':''}><div className="dw-leaf small">{m.role==='user'?'Z':<Leaf size={22}/>}</div><div><p>{m.text}</p><time>{m.time}</time></div></article>)}</div><div className="dw-chat-bottom"><div className="dw-prompts"><button onClick={()=>send('如何上传卫星图？')}>如何上传卫星图？</button><button onClick={()=>send('可以识别哪些要素？')}>可以识别哪些要素？</button></div><form onSubmit={e=>{e.preventDefault();send()}}><input aria-label="输入你的问题或需求" placeholder="输入你的问题或需求…" value={message} onChange={e=>setMessage(e.target.value)}/><button aria-label="发送消息" disabled={!message.trim()}><Send size={21}/></button></form><small>演示助手 · 本机保存 · {saved}</small></div></div></aside>}</main>
  <Dialog open={!!dialog} onOpenChange={open=>{if(!open)setDialog('')}}><DialogContent className="dw-dialog"><DialogHeader><DialogTitle>{dialog==='gallery'?'村庄影像库':'检索源与服务状态'}</DialogTitle><DialogDescription>{dialog==='gallery'?'选择项目已有影像，或上传 GeoTIFF / PNG / JPG / WebP。文件仅保存于本机。':'当前 demo 使用本机资料与演示规则；以下状态反映实际接入情况。'}</DialogDescription></DialogHeader>{dialog==='gallery'?<><button className="dw-upload-area" disabled={busy} onClick={()=>upload.current?.click()}><Upload/><b>{busy?'正在读取影像…':'上传正射影像或卫星俯视图'}</b><span>GeoTIFF 读取坐标信息；普通图片需补充尺度。</span></button><div className="dw-gallery-grid">{project.photos.filter(p=>p.category==='卫星航拍图').map(p=><button key={p.id} onClick={()=>{onChange({...emptySpatial(project.address),mode:'upload',image:p.src,crs:'项目图片 · 坐标待确认'});setShowWelcome(false);setDialog('');setChatOpen(false)}}><img src={p.src} alt={p.name}/><span>{p.name}</span></button>)}<button onClick={()=>{onChange(demoSpatial());setShowWelcome(false);setDialog('');setChatOpen(false)}}><img src="/demo-orthophoto.png" alt="青溪村演示影像"/><span>青溪村 · 演示样例</span></button></div><button className="dw-secondary" onClick={onGallery}>管理档案图片库</button>{notice&&<p role="status">{notice}</p>}</>:<div className="dw-source-list">{[['项目档案','本机资料可用'],['路径与覆盖计算','演示规则已接入'],['AI 视觉 / 图片编辑','未接入 · 使用预制演示素材'],['公开高程 / 地理编码','未接入 · 需人工确认'],['外部知识库 / 多人协作','未接入']].map(([title,status])=><div key={title}><b>{title}</b><span>{status}</span></div>)}</div>}</DialogContent></Dialog>
  <input className="hidden" ref={upload} type="file" accept=".tif,.tiff,image/png,image/jpeg,image/webp" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setBusy(true);try{onChange(await importMap(f,project.address));setShowWelcome(false);setDialog('');setChatOpen(false)}catch(error){setNotice(`无法读取此文件：${error instanceof Error?error.message:'请检查图片格式'}`)}finally{setBusy(false);e.target.value=''}}}/>
 </div>
}
