'use client';
import {useRef,useState,useEffect} from 'react';
import {ArrowRight,Check,ChevronDown,MapPin,Route,Building2,Flag,MousePointer2,Plus,Trash2,Scissors,GitMerge,Play,Download,Save,History,Image as ImageIcon,Upload,ArrowLeft,PanelRightClose,PanelRightOpen,CheckCircle2,Info} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import SpatialMap from './spatial-map';
import {emptySpatial,demoSpatial,hasMetricScale,defaultConfig,calculateRoute,evaluateSite,nearestNode,distance,snapshot,buildingKinds,hazardKinds,RULE_VERSION,type Spatial,type Point,type Road,type Building,type Hazard,type Config,type Snapshot} from '@/lib/spatial';

export type EditorProps={data:Spatial;onChange:(s:Spatial)=>void;onPlan:(title:string,body:string)=>void;onEmpty:()=>void;chatOpen:boolean;onToggleChat:()=>void;onSelection?:(id:string)=>void;focusId?:string;};
const steps=['项目定位','路网校正','空间标记','路径测试','选址测试','场域设计'];
const uid=(prefix:string)=>`${prefix}-${crypto.randomUUID().slice(0,8)}`;
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="dw-field"><span>{label}</span>{children}</label>}
function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <Field label={label}><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></Field>}
function fileImage(file:File):Promise<string>{return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(new Error('图片读取失败'));r.readAsDataURL(file)});}
export async function importMap(file:File,address:string):Promise<Spatial>{
 const s=emptySpatial(address);s.mode='upload';
 if(/\.tiff?$/i.test(file.name)){
  const {fromArrayBuffer}=await import('geotiff');const tiff=await fromArrayBuffer(await file.arrayBuffer());const img=await tiff.getImage();const geo=img.getGeoKeys();const width=Math.min(img.getWidth(),1800),height=Math.round(img.getHeight()*width/img.getWidth());const rgb=await img.readRGB({width,height,interleave:true});const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const context=canvas.getContext('2d')!;const pixels=context.createImageData(width,height);for(let i=0;i<width*height;i++){pixels.data[i*4]=Number(rgb[i*3]);pixels.data[i*4+1]=Number(rgb[i*3+1]);pixels.data[i*4+2]=Number(rgb[i*3+2]);pixels.data[i*4+3]=255;}context.putImageData(pixels,0,0);s.image=canvas.toDataURL('image/jpeg',.92);const epsg=geo?.ProjectedCSTypeGeoKey??geo?.GeographicTypeGeoKey;s.crs=epsg?`EPSG:${epsg}`:'未读取到坐标系';const box=img.getBoundingBox();s.address=address;s.audit=[{time:new Date().toISOString(),actor:'本机导入',action:`GeoTIFF：${file.name}`,before:'无底图',after:`${img.getWidth()} × ${img.getHeight()}；${s.crs}；范围 ${box.join(', ')}`}];if(geo?.ProjLinearUnitsGeoKey===9001&&geo.ProjectedCSTypeGeoKey){s.scale=Math.abs(box[2]-box[0])/1000;s.calibration={status:'unknown',source:'GeoTIFF 米制范围已读取，需核验影像轴向与配准',unit:'m',scaleY:Math.abs(box[3]-box[1])/667};}
 }else{s.image=await fileImage(file);s.crs='无坐标影像 · 需人工补充';}
 return s;
}

export default function SpatialEditor({data:s,onChange,onPlan,onEmpty,chatOpen,onToggleChat,onSelection,focusId}:EditorProps){
 const [step,setStep]=useState('路网校正'),[tool,setTool]=useState('select'),[selected,setSelected]=useState(s.roads[0]?.id||''),[roadStart,setRoadStart]=useState<Point|null>(null),[tested,setTested]=useState(false),[preference,setPreference]=useState<'shortest'|'safe'|'habit'>('shortest'),[modal,setModal]=useState(''),[notice,setNotice]=useState(''),[historyId,setHistoryId]=useState(''),[busy,setBusy]=useState(false),[facilityName,setFacilityName]=useState('树荫休息点'),[size,setSize]=useState<'小'|'中'|'大'>('小'),[scenePhoto,setScenePhoto]=useState(''),[effect,setEffect]=useState(false),[layoutSelection,setLayoutSelection]=useState(''),[layoutKind,setLayoutKind]=useState('扶手长椅'),[newHazard,setNewHazard]=useState('积水'),[mergeId,setMergeId]=useState('');
 useEffect(()=>{onSelection?.(selected)},[selected,onSelection]);
 useEffect(()=>{if(focusId){setSelected(focusId);setStep('路网校正')}},[focusId]);
 const photoInput=useRef<HTMLInputElement>(null),mapInput=useRef<HTMLInputElement>(null),hazardInput=useRef<HTMLInputElement>(null);const layoutDrag=useRef<string|null>(null);
 const road=s.roads.find(r=>r.id===selected),building=s.buildings.find(b=>b.id===selected),hazard=s.hazards.find(h=>h.id===selected);
 const corrected=s.roads.length>0&&s.roads.every(r=>r.confirmed);const config=s.config;
 const routes={shortest:calculateRoute(s,config,'shortest'),safe:calculateRoute(s,config,'safe'),habit:calculateRoute(s,config,'habit')};const result=routes[preference];const evaluation=s.facility?evaluateSite(s,s.facility):null;
 function change(patch:Partial<Spatial>,action:string,before='',after=''){onChange({...s,...patch,version:s.version+1,audit:[...s.audit,{time:new Date().toISOString(),actor:'张工（本机演示）',action,before,after}]});setTested(false);}
 function saveVersion(name:string,patch:Partial<Spatial>={}){const next={...s,...patch,version:s.version+1};const version=snapshot(next,name,'用户保存场景');onChange({...next,history:[...s.history,version],audit:[...s.audit,{time:version.time,actor:version.actor,action:`保存版本：${name}`,before:`V${s.version}`,after:`V${next.version}`}]});setNotice(`已保存「${name}」，可在版本记录中比较。`);}
 function updateRoad(patch:Partial<Road>){if(!road)return;change({roads:s.roads.map(r=>r.id===road.id?{...r,...patch,confirmed:false}:r)},`编辑道路 ${road.id}`,JSON.stringify(road),JSON.stringify(patch));}
 function updateBuilding(patch:Partial<Building>){if(!building)return;change({buildings:s.buildings.map(b=>b.id===building.id?{...b,...patch}:b)},`编辑建筑 ${building.id}`,JSON.stringify(building),JSON.stringify(patch));}
 function updateHazard(patch:Partial<Hazard>){if(!hazard)return;change({hazards:s.hazards.map(h=>h.id===hazard.id?{...h,...patch}:h)},`编辑标点 ${hazard.id}`,JSON.stringify(hazard),JSON.stringify(patch));}
 function setConfig(patch:Partial<Config>){change({config:{...config,...patch}},'修改测试配置',JSON.stringify(config),JSON.stringify(patch));}
 function select(id:string){setSelected(id);if(id.startsWith('SP-'))setStep('空间标记');}
 function place(p:Point){
  if(tool==='road'){
   if(!roadStart){setRoadStart(p);setNotice('已选起点，请点击道路终点。');return;}
   const nodes=[...s.nodes];const snap=(p:Point)=>{const n=nearestNode({nodes},p);if(n&&distance(n,p)<24)return n.id;const id=uid('N');nodes.push({...p,id,name:`自定义节点 ${nodes.length+1}`});return id;};const a=snap(roadStart),b=snap(p);setRoadStart(null);if(a===b){setNotice('起终点需不同，请重新绘制。');return;}if(s.roads.some(r=>r.a===a&&r.b===b||r.a===b&&r.b===a)){setNotice('这两个节点已连接。');return;}const r:Road={id:uid('R'),a,b,width:null,source:'用户绘制',access:'未知',confirmed:false,steps:null,lit:null};change({nodes,roads:[...s.roads,r]},'补画道路','',JSON.stringify(r));setSelected(r.id);setNotice('已补画道路，请填写宽度并确认。');
  }else if(tool==='building'){const b:Building={...p,id:uid('B'),w:38,h:30,name:'新增建筑',kind:'未分类',elderly:0};change({buildings:[...s.buildings,b]},'新增建筑','',JSON.stringify(b));setSelected(b.id);}
  else if(tool==='hazard'){const h:Hazard={...p,id:uid('SP'),road:road?.id||'',kind:newHazard,environment:'日常',status:'待核实',note:'',source:'用户标点'};change({hazards:[...s.hazards,h]},'新增特殊情况','',JSON.stringify(h));setSelected(h.id);setTool('select');}
  else if(tool==='facility'){change({facility:{...p,name:facilityName.trim()||'候选设施',size,angle:s.facility?.angle||0}},'试放候选设施');}
 }
 function splitRoad(){if(!road)return;const a=s.nodes.find(n=>n.id===road.a)!,b=s.nodes.find(n=>n.id===road.b)!;const id=uid('N'),r1={...road,id:uid('R'),b:id,confirmed:false},r2={...road,id:uid('R'),a:id,confirmed:false};change({nodes:[...s.nodes,{id,name:'拆分节点',x:(a.x+b.x)/2,y:(a.y+b.y)/2}],roads:[...s.roads.filter(r=>r.id!==road.id),r1,r2],hazards:s.hazards.map(h=>h.road===road.id?{...h,road:distance(h,a)<distance(h,b)?r1.id:r2.id}:h)},'拆分道路',road.id,`${r1.id} / ${r2.id}`);setSelected(r1.id);}
 function mergeRoad(){const other=s.roads.find(r=>r.id===mergeId);if(!road||!other)return;const shared=[road.a,road.b].find(n=>n===other.a||n===other.b);if(!shared||s.roads.filter(r=>r.a===shared||r.b===shared).length!==2){setNotice('仅可合并相邻且连接点无分叉的道路。');return;}if(['width','access','steps','lit','source'].some(k=>road[k as keyof Road]!==other[k as keyof Road])){setNotice('两段道路属性不同，请保留分段以便测试。');return;}const merged={...road,a:road.a===shared?road.b:road.a,b:other.a===shared?other.b:other.a,confirmed:false};change({roads:s.roads.filter(r=>r.id!==other.id).map(r=>r.id===road.id?merged:r),hazards:s.hazards.map(h=>h.road===other.id?{...h,road:road.id}:h)},'合并道路',`${road.id} / ${other.id}`,road.id);setMergeId('');}
 function textPlan(){return `# ${s.facility?.name||'青溪村公共广场'} · 适老化概念方案\n\n场景版本 V${s.version}；规则 ${RULE_VERSION}；本机演示，非工程结论。\n\n## 现状与问题\n已记录 ${s.roads.length} 段道路、${s.buildings.length} 处建筑、${s.hazards.length} 个特殊情况点。\n${s.hazards.filter(h=>h.status!=='已否定').map(h=>`- ${h.id} / ${h.road}：${h.kind}（${h.status}），${h.note||'待补充现场说明'}；证据：${h.source}${h.photo?'，已绑定照片':''}`).join('\n')}\n\n## 设计目标\n${s.goal}\n\n## 空间组织\n${s.layout.map(l=>`- ${l.kind}：布局相对位置 ${Math.round(l.x)}%, ${Math.round(l.y)}%（非工程尺寸）`).join('\n')}\n\n## 设施与做法\n${s.preserve}。保留连续的主通行空间，根据已确认布局增补休息、遮阳与照明设施。\n\n## 适老化考虑\n角色：${config.role} / ${config.vision}；环境：${config.environment}。${corrected?'已人工确认演示路网。':'路网尚未确认，以下仅为预览。'}\n最短路线：${routes.shortest.reachable?(routes.shortest.length===null?'尺度未知':Math.round(routes.shortest.length))+' 米':'不可达'}；相对低风险路线：${routes.safe.reachable?(routes.safe.length===null?'尺度未知':Math.round(routes.safe.length))+' 米':'不可达'}。${hasMetricScale(s)?`距离基于 ${s.scale} 米/图像单位的${s.mode==='demo'?'演示':'用户标定'}尺度。`:'尺度未知，仅提供拓扑预览。'}\n${evaluation?`候选点：${evaluation.label}；400 米演示范围覆盖 ${evaluation.status==='gray'?'—':evaluation.coverage} 人；${evaluation.reason}`:'尚未确认新增设施选址。'}\n\n## 材料与维护\n预算等级：${s.budget}。优先选择当地可采购、耐久、便于维护的常见材料；具体材料、采购和维护责任由项目各方确认。\n\n## 实施阶段\n近期：核对台阶、雨后积水及有效宽度，整理现场证据。\n中期：复核场地尺度后实施休息、遮阳、照明等设施。\n长期：组织使用反馈与定期维护。\n\n## 待复核事项\n公开高程未接入，局部坡度未知；现场尺寸、排水、结构、土地、规划及审批均待专业复核。虚拟角色不代表真实老人，不预测事故概率。效果图为预制 AI 演示示例，不随用户布局或照片自动生成；本方案不作为建设许可、施工图或工程依据。\n\n## 证据与版本\n${s.audit.slice(-12).map(a=>`${a.time} · ${a.actor} · ${a.action}`).join('\n')}`;}
 function exportFile(name:string,content:string,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice(`已导出 ${name}`);}
 async function uploadScene(file:File|undefined){if(!file)return;setScenePhoto(await fileImage(file));setEffect(false);setNotice('已载入现状照片。可编辑布局；当前尚未接入在线 AI 图片编辑。');}
 const versions=s.history;const compare=versions.find(v=>v.id===historyId);
 return <div className="dw-editor">
 <div className="dw-editor-heading"><div><span>调试 WORKSPACE <em>{s.mode==='demo'?'演示项目':'本机项目'}</em></span><h1>空间调试台</h1><p>从真实资料出发，让每一次空间判断都有依据。</p></div><button className="dw-icon-button" title={chatOpen?'收起助手':'展开助手'} aria-label={chatOpen?'收起助手':'展开助手'} onClick={onToggleChat}>{chatOpen?<PanelRightClose/>:<PanelRightOpen/>}</button></div>
 <Tabs value={step} onValueChange={v=>{setStep(String(v));setTool(v==='选址测试'?'facility':'select');setRoadStart(null)}}><TabsList className="dw-steps">{steps.map((v,i)=><TabsTrigger key={v} value={v}><span>{String(i+1).padStart(2,'0')}</span>{v}</TabsTrigger>)}</TabsList></Tabs>
 <div className="dw-editor-body">
 {step==='场域设计'?<div className="dw-design">
 <div className="dw-section-top"><div><h3>把空间想法，变成可讨论的方案</h3><p>选定现状视角，编辑概念布局，并说明每一项改变。</p></div><button className="dw-secondary" onClick={()=>photoInput.current?.click()}><Upload size={14}/>上传现状图</button></div>
 <div className="dw-scene-photo"><img src={scenePhoto||(effect?'/demo-courtyard-after.png':'/demo-courtyard-before.png')} alt={effect?'预制适老化概念效果示例':'场域现状照片'}/><span>{scenePhoto?'用户现状照片':effect?'AI 概念示例 · 预制演示素材':'青溪村现状 · AI 生成演示素材'}</span>{!scenePhoto&&<div className="dw-photo-switch"><button className={!effect?'active':''} onClick={()=>setEffect(false)}>现状</button><button className={effect?'active':''} onClick={()=>setEffect(true)}>概念示例</button></div>}</div>
 <div className="dw-design-columns"><div><h3>大致布局 <small>拖动组件调整位置</small></h3><div className="dw-layout" onPointerMove={e=>{if(!layoutDrag.current)return;const r=e.currentTarget.getBoundingClientRect();onChange({...s,layout:s.layout.map(l=>l.id===layoutDrag.current?{...l,x:Math.max(5,Math.min(95,(e.clientX-r.left)/r.width*100)),y:Math.max(8,Math.min(92,(e.clientY-r.top)/r.height*100))}:l)});}} onPointerUp={()=>{if(layoutDrag.current){layoutDrag.current=null;change({},'调整布局组件位置');}}}><span className="dw-layout-label">保留建筑与场地边界</span><span className="dw-layout-entry">主入口 / 保持通行</span>{s.layout.map(l=><button key={l.id} className={l.id===layoutSelection?'selected':''} style={{left:`${l.x}%`,top:`${l.y}%`}} onPointerDown={e=>{e.currentTarget.parentElement!.setPointerCapture(e.pointerId);layoutDrag.current=l.id;setLayoutSelection(l.id);}} onKeyDown={e=>{const d:Record<string,Point>={ArrowLeft:{x:-2,y:0},ArrowRight:{x:2,y:0},ArrowUp:{x:0,y:-2},ArrowDown:{x:0,y:2}};if(d[e.key]){e.preventDefault();change({layout:s.layout.map(v=>v.id===l.id?{...v,x:Math.max(5,Math.min(95,v.x+d[e.key].x)),y:Math.max(8,Math.min(92,v.y+d[e.key].y))}:v)},'键盘调整布局');}}}><MapPin size={15}/>{l.kind}</button>)}</div><div className="dw-inline"><select aria-label="布局组件类型" value={layoutKind} onChange={e=>setLayoutKind(e.target.value)}>{['扶手长椅','遮阳棚','照明','绿化','标识','保留树木'].map(v=><option key={v}>{v}</option>)}</select><button className="dw-secondary" onClick={()=>change({layout:[...s.layout,{id:uid('l'),kind:layoutKind,x:50,y:50}]},'增加布局组件','',layoutKind)}><Plus size={14}/>添加</button><button className="dw-secondary" disabled={!layoutSelection} aria-label="删除布局组件" onClick={()=>{change({layout:s.layout.filter(l=>l.id!==layoutSelection)},'移除布局组件',layoutSelection);setLayoutSelection('')}}><Trash2 size={14}/></button></div><p className="dw-note">布局用于讨论功能与大致位置；无施工尺寸。概念示例为预制素材，不随布局变化。</p></div><div className="dw-form"><Field label="设计目标"><textarea value={s.goal} onChange={e=>change({goal:e.target.value},'更新设计目标')}/></Field><Select label="预算等级" value={s.budget} options={['低','中','高']} onChange={v=>change({budget:v},'更新预算等级')}/><Field label="保留对象与不可改变区域"><textarea value={s.preserve} onChange={e=>change({preserve:e.target.value},'更新保留对象')}/></Field><button className="dw-primary" onClick={()=>setModal('plan')}><FilePlanIcon/>生成文字方案</button></div></div>
 </div>:<>
 <div className="dw-toolbar"><div>{[{id:'select',name:'选择',icon:MousePointer2},{id:'road',name:'补画道路',icon:Route},{id:'building',name:'建筑',icon:Building2},{id:'hazard',name:'特殊情况',icon:MapPin}].map(({id,name,icon:Icon})=><button key={id} className={tool===id?'active':''} onClick={()=>{setTool(id);setRoadStart(null);if(id==='road')setStep('路网校正');if(id==='building'||id==='hazard')setStep('空间标记')}}><Icon size={15}/><span>{name}</span></button>)}</div><span className={corrected?'dw-status good':'dw-status'}>{corrected?<CheckCircle2 size={13}/>:<Info size={13}/>} {corrected?'路网已确认':'路网待校正'}</span></div>
 <div className="dw-map-and-info"><SpatialMap data={s} selected={selected} tool={tool} route={tested?result:undefined} onSelect={select} onPoint={place} onMoveFacility={p=>onChange({...s,facility:s.facility?{...s.facility,...p}:null})}/>
 <div className="dw-inspector">
 {step==='项目定位'?<><div className="dw-inspector-title"><MapPin size={17}/><h3>项目定位与底图</h3></div><Field label="村庄地址"><textarea value={s.address} onChange={e=>change({address:e.target.value,locationConfirmed:false},'更新项目地址')}/></Field><Field label="坐标参考系"><input value={s.crs} onChange={e=>change({crs:e.target.value},'更新坐标参考')}/></Field><Field label="地图宽度对应实际距离（米）"><input type="number" min="1" value={hasMetricScale(s)?s.scale*1000:''} placeholder="未知，输入实测宽度" onChange={e=>{if(+e.target.value>0)change({scale:+e.target.value/1000,calibration:{status:'manual',source:'用户输入地图宽度标定',unit:'m'}},'更新地图尺度')}}/></Field><button className="dw-primary" onClick={()=>change({locationConfirmed:true},'确认位置与研究范围',s.address,'用户已确认')}><Check size={14}/>{s.locationConfirmed?'位置已确认':'确认位置与研究范围'}</button><div className="dw-info-card"><b>高程资料 · 未接入</b><p>GLO-30 / SRTM / AW3D30 数据接口待接入。当前不输出高程、局部坡度或工程尺寸。</p><p>{s.mode==='demo'?'底图及尺度为模拟演示，不对应真实青溪村。':'当前以整幅影像作为研究范围，需人工确认尺度及坐标。'}</p></div><button className="dw-secondary" onClick={()=>mapInput.current?.click()}><Upload size={14}/>更换底图</button></>:
 step==='路网校正'?<><div className="dw-inspector-title"><Route size={17}/><h3>道路属性</h3></div><Field label="选择道路"><select value={road?.id||''} onChange={e=>setSelected(e.target.value)}><option value="" disabled>选择一段道路</option>{s.roads.map(r=><option key={r.id} value={r.id}>{r.id} · {r.confirmed?'已确认':'待校正'}</option>)}</select></Field>{road?<><div className="dw-object-id">{road.id}<span>{road.source}</span></div><Field label="有效通行宽度（米；留空为未知）"><input type="number" step="0.1" min="0.1" value={road.width??''} placeholder="未知" onChange={e=>{if(!e.target.value||+e.target.value>0)updateRoad({width:e.target.value?+e.target.value:null})}}/></Field><Select label="数据性质" value={road.source} options={['演示估计','实测','用户估计','图片判断','村民说明','未知','用户绘制']} onChange={source=>updateRoad({source})}/><Select label="通行属性" value={road.access} options={['未知','公开通行','私人使用','季节性通行','条件通行','不可通行']} onChange={access=>updateRoad({access})}/><Select label="台阶情况" value={road.steps===null?'未知':road.steps?'有':'无'} options={['未知','有','无']} onChange={v=>updateRoad({steps:v==='未知'?null:v==='有'})}/><Select label="照明情况" value={road.lit===null?'未知':road.lit?'有':'无'} options={['未知','有','无']} onChange={v=>updateRoad({lit:v==='未知'?null:v==='有'})}/><div className="dw-inline"><button className="dw-secondary" onClick={splitRoad}><Scissors size={13}/>拆分</button><button className="dw-secondary" onClick={()=>{change({roads:s.roads.filter(r=>r.id!==road.id),hazards:s.hazards.map(h=>h.road===road.id?{...h,road:'',status:'待核实'}:h)},'删除候选道路',road.id);setSelected('')}}><Trash2 size={13}/>删除</button></div><div className="dw-inline"><select aria-label="合并相邻道路" value={mergeId} onChange={e=>setMergeId(e.target.value)}><option value="">选择合并段</option>{s.roads.filter(r=>r.id!==road.id&&(r.a===road.a||r.b===road.a||r.a===road.b||r.b===road.b)).map(r=><option key={r.id}>{r.id}</option>)}</select><button className="dw-secondary" disabled={!mergeId} onClick={mergeRoad}><GitMerge size={14}/></button></div><button className="dw-primary" onClick={()=>change({roads:s.roads.map(r=>r.id===road.id?{...r,confirmed:true}:r)},'确认道路',road.id,'已校正')}><Check size={14}/>确认此道路</button></>:<p className="dw-note">选择已有道路，或在地图上补画两个端点。</p>}<button className="dw-secondary full" disabled={!s.roads.length} onClick={()=>{const roads=s.roads.map(r=>({...r,confirmed:true}));const next={...s,roads};saveVersion('现状 V0 · 路网已校正',next);setNotice('已确认当前全部道路，可进行路径压力测试。')}}><CheckCircle2 size={14}/>已核对，确认全部路网</button><p className="dw-note">未确认路网仍可预览路线；正式诊断需先校正。改动道路后需再次确认。</p></>:
 step==='空间标记'?<><div className="dw-inspector-title"><Building2 size={17}/><h3>{hazard?'特殊情况':'建筑与现场证据'}</h3></div><Select label="新标点类型" value={newHazard} options={hazardKinds} onChange={v=>{setNewHazard(v);setTool('hazard')}}/>
 {hazard?<><div className="dw-object-id">{hazard.id}<span>{hazard.source}</span></div><Select label="特殊情况类型" value={hazard.kind} options={hazardKinds} onChange={kind=>updateHazard({kind})}/><Field label="关联道路"><select value={hazard.road} onChange={e=>updateHazard({road:e.target.value})}><option value="">独立点位</option>{s.roads.map(r=><option key={r.id}>{r.id}</option>)}</select></Field><Select label="触发场景" value={hazard.environment} options={['日常','雨后','夜间','农忙']} onChange={environment=>updateHazard({environment})}/><Field label="现场说明 / 候选事实"><textarea value={hazard.note} onChange={e=>updateHazard({note:e.target.value})}/></Field><button className="dw-secondary full" onClick={()=>hazardInput.current?.click()}><Upload size={14}/>{hazard.photo?'更换证据照片':'绑定证据照片'}</button>{hazard.photo&&<img className="dw-evidence-photo" src={hazard.photo} alt="当前特殊情况证据照片"/>}<Select label="用户确认状态" value={hazard.status} options={['待核实','已确认','已修改','已否定','已解决','暂不处理']} onChange={status=>updateHazard({status})}/><p className="dw-note">AI 视觉接口未接入。演示候选与人工事实分开记录；未确认观察显示为资料缺口。</p></>:<><Field label="选择建筑"><select value={building?.id||''} onChange={e=>setSelected(e.target.value)}><option value="">选择建筑</option>{s.buildings.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></Field>{building?<><Field label="建筑名称"><input value={building.name} onChange={e=>updateBuilding({name:e.target.value})}/></Field><Select label="建筑功能" value={building.kind} options={buildingKinds} onChange={kind=>updateBuilding({kind,elderly:kind.includes('老人')?building.elderly:0})}/>{building.kind.includes('老人')&&<Field label="大致老人人数（聚合）"><input type="number" min="0" step="1" value={building.elderly} onChange={e=>updateBuilding({elderly:Math.max(0,Math.round(+e.target.value))})}/></Field>}<div className="dw-inline"><Field label="轮廓宽"><input type="number" min="5" value={building.w} onChange={e=>updateBuilding({w:Math.max(5,+e.target.value)})}/></Field><Field label="轮廓高"><input type="number" min="5" value={building.h} onChange={e=>updateBuilding({h:Math.max(5,+e.target.value)})}/></Field></div><button className="dw-secondary" onClick={()=>{change({buildings:s.buildings.filter(b=>b.id!==building.id)},'移除建筑',building.id);setSelected('')}}><Trash2 size={14}/>移除此建筑</button></>:<p className="dw-note">点击建筑编辑分类；点击风险点绑定现场照片、确认或否定候选观察。</p>}</>}
 <div className="dw-info-card"><b>{s.buildings.filter(b=>b.elderly>0).length} 处老人居住点 · {s.buildings.reduce((v,b)=>v+b.elderly,0)} 人</b><p>仅保存聚合人数，不采集个人敏感信息。</p></div></>:
 step==='路径测试'?<><div className="dw-inspector-title"><Route size={17}/><h3>虚拟测试角色</h3></div><Select label="移动能力" value={config.role} options={['独立步行','拄杖','耐力较弱','使用助行器']} onChange={role=>setConfig({role})}/><Select label="感知条件" value={config.vision} options={['一般视力','低视力','夜间识别较弱']} onChange={vision=>setConfig({vision})}/><Select label="环境条件" value={config.environment} options={['日常','雨后','夜间','农忙']} onChange={environment=>setConfig({environment})}/><div className="dw-inline"><Select label="熟悉程度" value={config.familiarity} options={['熟悉','部分熟悉','不熟悉']} onChange={familiarity=>setConfig({familiarity})}/><Select label="携带情况" value={config.carrying} options={['无','购物袋','菜篮']} onChange={carrying=>setConfig({carrying})}/></div>{(['start','end'] as const).map(k=><Field key={k} label={k==='start'?'起点':'终点'}><select value={config[k]} onChange={e=>setConfig({[k]:e.target.value})}>{s.nodes.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></Field>)}<Field label="习惯路线（按顺序选择节点）"><div className="dw-habit">{config.habit.map((n,i)=><button key={`${i}-${n}`} title="点击移除此节点" onClick={()=>setConfig({habit:config.habit.filter((_,j)=>i!==j)})}>{s.nodes.find(v=>v.id===n)?.name||n} ×</button>)}</div><select value="" onChange={e=>{if(e.target.value)setConfig({habit:[...config.habit,e.target.value]})}}><option value="">添加途经节点…</option>{s.nodes.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></Field><button className="dw-primary" disabled={!s.roads.length} onClick={()=>{setTested(true);setNotice(corrected?'已完成当前角色与环境的路径压力测试。':'已生成预览路线；路网未确认，暂不形成正式诊断。')}}><Play size={14}/>{corrected?'运行路径压力测试':'预览候选路线'}</button><p className="dw-note">规则 {RULE_VERSION} 为可解释演示权重。虚拟角色不代表真实老人，不预测真实事故概率。</p></>:
 <><div className="dw-inspector-title"><Flag size={17}/><h3>新增候选设施</h3></div><Field label="拟建设内容"><input value={facilityName} onChange={e=>{setFacilityName(e.target.value);if(s.facility)change({facility:{...s.facility,name:e.target.value}},'修改候选设施名称')}}/></Field><div className="dw-size-options">{(['小','中','大'] as const).map(v=><button key={v} className={size===v?'active':''} onClick={()=>{setSize(v);if(s.facility)change({facility:{...s.facility,size:v}},'修改设施面积档')}}>{v}<small>约 {({小:36,中:81,大:144})[v]} m²</small></button>)}</div><p className="dw-note">面积是演示配置档位，可在地图试放或拖动轮廓。</p>{s.facility&&<Field label={`旋转角度 ${s.facility.angle}°`}><input type="range" min="0" max="180" step="5" value={s.facility.angle} onChange={e=>change({facility:{...s.facility!,angle:+e.target.value}},'旋转设施轮廓')}/></Field>}<button className="dw-secondary full" onClick={()=>{setTool('facility');place({x:478,y:270})}}><MapPin size={14}/>试放到广场</button>{evaluation&&<div className={`dw-site-result ${evaluation.status}`}><b><i/>{evaluation.label}</b><p>{evaluation.reason}</p><div><strong>{evaluation.status==='gray'?'—':evaluation.coverage}<small>覆盖人数</small></strong><strong>{(evaluation.status==='gray'?'—':Math.round(evaluation.worst))} m<small>最差可达路线</small></strong></div><p>接入道路 {evaluation.road} · 平均路线约 {(evaluation.status==='gray'?'—':Math.round(evaluation.average))} m · 未覆盖 {evaluation.status==='gray'?'—':evaluation.uncovered} 人</p></div>}<button className="dw-primary" disabled={!s.facility||evaluation?.status==='red'||evaluation?.status==='gray'} onClick={()=>{saveVersion(`候选选址 · ${s.facility!.name}`);setNotice('候选点已保存为独立场景版本，覆盖与到达路线已重新计算。')}}><Save size={14}/>确认选址并保存版本</button><p className="dw-note">仅评价已录入适老化通达性、服务覆盖与空间关系。不涉及用地、规划、产权、消防、工程及审批。</p></>}
 </div></div>
 {step==='路径测试'&&tested&&<div className="dw-test-results"><div className="dw-result-heading"><h3>{corrected?'路径压力测试结果':'候选路线预览'} <small>V{s.version} · {config.role} · {config.environment}</small></h3><span>{corrected?'示例规则计算':'路网待校正'}</span></div><div className="dw-route-cards">{(['shortest','safe','habit'] as const).map((key,i)=>{const r=routes[key];return <button key={key} className={preference===key?'active':''} onClick={()=>setPreference(key)}><span>{['最短候选路线','相对低风险路线','用户习惯路线'][i]}</span><strong>{r.length!==null?Math.round(r.length):'—'} <small>{r.reachable?(r.length===null?'尺度未知':'m'):'当前不可达'}</small></strong><small>{r.reachable?`${r.events.filter(e=>e.category!=='数据缺口').length} 项问题 · ${r.unknown} 项资料缺口`:'核对连通性、起终点与角色限制'}</small></button>})}</div>{corrected&&<div className="dw-issue-list">{result.events.map((e,i)=><article key={`${e.road}-${i}`}><span className={e.category==='数据缺口'?'gap':'risk'}>{e.category}</span><div><b>{e.road} · {e.kind}</b><p>{e.advice}</p><small>证据：{e.source} · 严重程度：{e.severity} · 置信度：{e.category==='数据缺口'?'低':'依赖用户输入'} · {RULE_VERSION}</small></div><button title="定位相关道路" onClick={()=>{setSelected(e.road);setStep('路网校正')}}><MapPin size={16}/></button></article>)}{!result.events.length&&<p className="dw-note">{result.reachable?'本次规则未检出已录入问题，不代表已排除现场风险。':'当前任务不可达，请检查路网和角色限制。'}</p>}</div>}</div>}
 </>}
 </div>
 <footer className="dw-editor-footer"><span><i/>本机演示 · V{s.version}</span><button onClick={()=>setModal('history')}><History size={14}/>版本记录 <b>{versions.length}</b></button><button onClick={()=>saveVersion(`场景 V${s.version}`)}><Save size={14}/>保存</button><button onClick={()=>exportFile('乡筑-场景数据.json',JSON.stringify(s,null,2),'application/json')}><Download size={14}/>导出</button><button onClick={onEmpty}>返回</button><button className="dw-next" onClick={()=>{const next=steps[(steps.indexOf(step)+1)%steps.length];setStep(next);setTool(next==='选址测试'?'facility':'select')}}>{step==='场域设计'?'项目定位':'下一步'}<ArrowRight size={14}/></button></footer>
 {notice&&<button className="dw-inline-notice" role="status" onClick={()=>setNotice('')}>{notice}<span>×</span></button>}
 <input className="hidden" ref={photoInput} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>uploadScene(e.target.files?.[0])}/><input className="hidden" ref={hazardInput} type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{if(e.target.files?.[0])updateHazard({photo:await fileImage(e.target.files[0])})}}/><input className="hidden" ref={mapInput} type="file" accept=".tif,.tiff,image/png,image/jpeg,image/webp" onChange={async e=>{if(!e.target.files?.[0])return;try{setBusy(true);const data=await importMap(e.target.files[0],s.address);onChange({...data,history:[...s.history,snapshot(s,'更换底图前','保留原始场景')],audit:[...s.audit,...data.audit]});setSelected('');setStep('项目定位');}catch(error){setNotice(`导入失败：${error instanceof Error?error.message:'无法读取此影像'}`)}finally{setBusy(false)}}}/>
 <Dialog open={!!modal} onOpenChange={open=>{if(!open)setModal('')}}><DialogContent className="dw-dialog"><DialogHeader><DialogTitle>{modal==='history'?'场景版本与操作记录':'场域概念文字方案'}</DialogTitle><DialogDescription>{modal==='history'?'保存完整场景快照，保留修改与确认的来源。':'根据当前场景与布局整理的本机模板方案，发送后仍保留证据编号。'}</DialogDescription></DialogHeader>{modal==='history'?<div className="dw-history"><Field label="选择历史版本"><select value={historyId} onChange={e=>setHistoryId(e.target.value)}><option value="">选择保存过的场景</option>{versions.map(v=><option key={v.id} value={v.id}>{v.name} · {new Date(v.time).toLocaleTimeString('zh-CN')}</option>)}</select></Field>{compare&&<><table><thead><tr><th>场景数据</th><th>{compare.name}</th><th>当前 V{s.version}</th></tr></thead><tbody>{[['道路',compare.roads.length,s.roads.length],['特殊情况',compare.hazards.length,s.hazards.length],['老人人数',compare.buildings.reduce((v,b)=>v+b.elderly,0),s.buildings.reduce((v,b)=>v+b.elderly,0)],['候选设施',compare.facility?.name||'无',s.facility?.name||'无']].map(([label,a,b])=><tr key={label}><td>{label}</td><td>{a}</td><td>{b}</td></tr>)}</tbody></table><button className="dw-primary" onClick={()=>{const {id,name,time,actor,reason,...content}=compare;change(structuredClone(content),`恢复场景：${name}`,`V${s.version}`,`来自 ${id}`);setModal('');setNotice(`已恢复「${name}」，原有历史版本保留。`)}}>恢复此场景</button></>}<h3>操作记录 · {s.audit.length} 条</h3>{s.audit.slice().reverse().map((a,i)=><article key={i}><b>{a.action}</b><p>{a.actor} · {new Date(a.time).toLocaleString('zh-CN')}</p><details><summary>查看变更内容</summary><pre>变更前：{a.before||'—'}{'\n'}变更后：{a.after||'—'}</pre></details></article>)}</div>:<><pre className="dw-plan-preview">{textPlan()}</pre><div className="dw-inline"><button className="dw-secondary" onClick={()=>exportFile('乡筑-概念方案.md',textPlan())}><Download size={15}/>导出 Markdown</button><button className="dw-primary" onClick={()=>{saveVersion(`场域设计 · ${s.facility?.name||'公共广场'}`);onPlan(`${s.facility?.name||'公共广场'} · 概念方案`,textPlan());setModal('')}}><ArrowRight size={15}/>发送到方案区</button></div></>}</DialogContent></Dialog>
 {busy&&<div className="dw-loading" role="status">正在读取影像与坐标信息…</div>}
 </div>
}
function FilePlanIcon(){return <ImageIcon size={15}/>}
